eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411
    enabled: false
    compression:
      enabled: true
feign:
  okhttp:
    enabled: true #开启OKHTTP支持，依赖 （feign-okhttp）默认HttpClient
  #请求和响应GZIP压缩支持
  compression:
    request:
      enabled: true
      #支持压缩的mime types
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true